name: "Build documentation"
on:
  push:
    branches: [ main ]
    
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  persist-credentials: false
                  submodules: recursive
                  
            - name: Set branch environment variable
              run: |
               currentBranch=$(git branch --show-current)
               now_date=$(date "+%Y-%m-%d_%H-%M-%S")

               echo "project_branch=${currentBranch}-${now_date}" >> ${GITHUB_ENV}

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  
            # 关注打包的指令
            - name: Build
              run: |
                  ls
                  echo ''
                  export NODE_OPTIONS=--max-old-space-size=8192
                  npm install 
                  npm run docs-build
                  ls
                  echo ''
                  tar -czvf build.tar.gz dist
                  ls

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1
              with:
                   tag: ${{ env.project_branch }}
                   allowUpdates: true
                   artifacts: "build.tar.gz"
                   token: ${{ github.token }}
                   generateReleaseNotes: true   
